# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/realme/ferrarri/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),ferrarri)

$(call add-radio-file-sha1-checked,radio/abl.img,2d25011964959eecc81cd7a78b6cfff146bede80)
$(call add-radio-file-sha1-checked,radio/aop.img,6dff98331c6b0d908aa800fb3ea21efc55708d10)
$(call add-radio-file-sha1-checked,radio/aop_config.img,f93ada2b9f6aaaba4a59952d64dd2db563d30a20)
$(call add-radio-file-sha1-checked,radio/bluetooth.img,ef3139293d16ce6b34fd44cbff84dd0972e5a414)
$(call add-radio-file-sha1-checked,radio/cpucp.img,38de138c08eb7e22ff166353f8fc39d9e3af27a3)
$(call add-radio-file-sha1-checked,radio/devcfg.img,5da11c92ea45cf2707f1f2fb53f9474c815bb356)
$(call add-radio-file-sha1-checked,radio/dsp.img,e9f84bc1929d77e5bcf2c8b184bfaed6c7942afb)
$(call add-radio-file-sha1-checked,radio/engineering_cdt.img,13f5f33df779408b04cdfb3d78dd1ebbd3afb7b4)
$(call add-radio-file-sha1-checked,radio/featenabler.img,2c9bd3620e0e8a47a5515d83a5971f330bc79ee0)
$(call add-radio-file-sha1-checked,radio/hyp.img,633e6c860a924127fa3248496ff63da66cd3a356)
$(call add-radio-file-sha1-checked,radio/imagefv.img,454420d2343d9b70be12f077de10d29abf0bda1f)
$(call add-radio-file-sha1-checked,radio/keymaster.img,9038f4e905a8f6dfd5da300d3fff0fe5222321c1)
$(call add-radio-file-sha1-checked,radio/modem.img,1423694943419261201cd2e720959de7180714a5)
$(call add-radio-file-sha1-checked,radio/oplus_sec.img,903e1685b64a523d629ac41fce6191b472b8a6e0)
$(call add-radio-file-sha1-checked,radio/oplusstanvbk.img,18a0b9d2b5a5365c25cf447e095af6bd0ea53cd2)
$(call add-radio-file-sha1-checked,radio/qupfw.img,d3bcb50f9c8c6190d81232df39cafc3a42334738)
$(call add-radio-file-sha1-checked,radio/shrm.img,c8b2c96a7ab143bdfc319e4b50996df23f2ede64)
$(call add-radio-file-sha1-checked,radio/splash.img,88b02f550aa70d1d51f8197ee83eb026c49f28e2)
$(call add-radio-file-sha1-checked,radio/tz.img,42d6efee60d9cfeab2c4d9ef2a41de8cb58d4036)
$(call add-radio-file-sha1-checked,radio/uefi.img,c3138b445860075075d3f1e7f6baa218d689fb3b)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,95bce0beeeba2903bd9795ad69ca094d773d1eb4)
$(call add-radio-file-sha1-checked,radio/xbl.img,b85fdf0e9e81888a0bb50319081abe14562d7dcb)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,3788f4686d475c1f354dd49d5a4bc0c753acbcfb)
$(call add-radio-file-sha1-checked,radio/xbl_ramdump.img,62f787793a76535bbe93ed30110518865d890584)

endif
